### PR TITLE
Fix round-trip failure of AES256_GCM_HKDF_4KB on Android 23.

### PR DESCRIPTION
**Pull request by mark-buer**
Fixes https://github.com/google/tink/issues/229

I'd love to add a test for this and remove the code comment, but, the effort and added complexity doesn't seem worth it for the size of the change.

### CODE REVIEW

**Comment by freygriff** [comment]
https://github.com/google/tink/pull/231/commits/59227a2bdfaf0216c213686cc7ee4dc4a76eead3

**Comment by przydatek** [comment]
Thanks Mark!

**Comment by tuancoltech** [comment]
Hi @mark-buer ,

This PR changes do not work in my case.
I rebuild tink source code which already includes your changes, but the exception still happens here in my app.

Do you have any further suggestion on how to deal with this?

Thanks.

**Comment by mark-buer** [comment]
Hi @tuancoltech 

We've successfully been using the [workaround](https://github.com/google/tink/issues/229#issuecomment-509074232) in our app.

This PR also fixes the issue we observed in devices in the wild.

It is possible that you've stumbled onto yet-another bug with Android's crypto implementation - it would not surprise me.

Sorry, I have nothing further to suggest.

**Pull request merged**
