### PR TITLE
Bazel Javascript rules

### PR DESCRIPTION
**Pull request by michaelfig**
Bazel rules now work for the Javascript, but the closure compiler throws an internal compiler error on the definition of `SecurityException` in `javascript/exception/securityexception.js`.

More work is needed, but this is a starting point, and I want to make sure there are no regressions in the rest of Tink.

#189 advice was followed to rearrange the order of `WORKSPACE`, but perhaps more can be done.

More advice is appreciated.

### CODE REVIEW

**Comment by michaelfig** [comment]
I have successfully run `bazel build ...` and all the targets build.  `bazel test ...` still fails (only 24/47 tests pass), but I have some ideas for fixing the tests.

I need my https://github.com/bazelbuild/rules_closure/pull/339 PR merged before I'd be able to use an unmodified upstream rules_closure.  When that happens, I will update the WORKSPACE accordingly.

**Comment by przydatek** [comment]
Hi Michael, sorry for the delay on this PR.  I'd be happy to proceed with review, but could you please resolve conflicts before that?

**Comment by michaelfig** [comment]
I've been away from this so long that I don't remember what changes are necessary to fix the build errors introduced by upstream.  The current branch has no more merge conflicts, but some Closure typing is still necessary to get `javascript/clearset_keyset_handle.js` to build.

Help would be appreciated... I'm not sure when I'll be able to resume work on Tink JS.

**Comment by michaelfig** [comment]
Here are the errors:

```
javascript/cleartext_keyset_handle.js:55: ERROR - could not determine the type of this expression
    return new KeysetHandle(PbKeyset.deserialize(keysetJspbString));
                            ^
  ProTip: "JSC_UNKNOWN_EXPR_TYPE" or "missingSourcesWarnings" or "reportUnknownTypes" can be added to the `suppress` attribute of:
  //javascript:cleartext_keyset_handle
  Alternatively /** @suppress {reportUnknownTypes} */ can be added to the source file.

javascript/cleartext_keyset_handle.js:55: ERROR - proto.google.crypto.tink.Keyset.deserialize is never defined
    return new KeysetHandle(PbKeyset.deserialize(keysetJspbString));
                            ^
  ProTip: "JSC_UNDEFINED_NAME" or "missingSourcesWarnings" or "undefinedNames" can be added to the `suppress` attribute of:
  //javascript:cleartext_keyset_handle
  Alternatively /** @suppress {undefinedNames} */ can be added to the source file.

javascript/cleartext_keyset_handle.js:55: ERROR - Property deserialize never defined on proto.google.crypto.tink.Keyset
    return new KeysetHandle(PbKeyset.deserialize(keysetJspbString));
                                     ^
  ProTip: "JSC_INEXISTENT_PROPERTY" or "checkTypes" or "missingProperties" or "missingSourcesWarnings" can be added to the `suppress` attribute of:
  //javascript:cleartext_keyset_handle
  Alternatively /** @suppress {missingProperties} */ can be added to the source file.

javascript/cleartext_keyset_handle.js:68: ERROR - could not determine the type of this expression
    return keysetHandle.getKeyset().serialize();
           ^
  ProTip: "JSC_UNKNOWN_EXPR_TYPE" or "missingSourcesWarnings" or "reportUnknownTypes" can be added to the `suppress` attribute of:
  //javascript:cleartext_keyset_handle
  Alternatively /** @suppress {reportUnknownTypes} */ can be added to the source file.

javascript/cleartext_keyset_handle.js:68: ERROR - Property serialize never defined on proto.google.crypto.tink.Keyset
    return keysetHandle.getKeyset().serialize();
                                    ^
  ProTip: "JSC_INEXISTENT_PROPERTY" or "checkTypes" or "missingProperties" or "missingSourcesWarnings" can be added to the `suppress` attribute of:
  //javascript:cleartext_keyset_handle
  Alternatively /** @suppress {missingProperties} */ can be added to the source file.

5 error(s), 0 warning(s), 97.4% typed
```

**Comment by thaidn** [comment]
Thanks a lot of working on this.

Based on this PR, we've come up with a new design that will allow us to build a NPM package. We're actively implementing this design and will open source what we've got soon.

Again, thanks for working on this!

**Comment by thaidn** [comment]
FYI: @taymonbeal has helped us publish a package, check out https://www.npmjs.com/package/tink-crypto.

**Pull request closed without merging**
