### PR TITLE
Some cleanup

### PR DESCRIPTION
**Pull request by docmerlin**
This is some cleanup after running `go vet` and `honnef.co/go/tools/cmd/megacheck`

Tests still will not pass because its missing some json files.

### CODE REVIEW

**Comment by dgryski** [comment]
The missing JSON files are from https://github.com/google/wycheproof

**Comment by docmerlin** [comment]
@dgryski  cool, yah when I `go get github.com/google/wycheproof` everything passes.  Added a better error message.
Anything preventing a merge?

**Comment by thaidn** [comment]
Thanks so much for making the code cleaner!

Just out of curiosity, how did you find out about Tink?

**Comment by docmerlin** [comment]
@thaidn dgryski mentioned it on the golang slack. :-)

**Comment by thaidn** [comment]
Thanks. I'm working toward 1.1.0 release of Java (and C++), but in 1-2 weeks I'll be working on (and learning) Go. The current code is not good, please do not use it for production :-)

**Comment by dgryski** [comment]
There are enough other people interested in this project that the Go code will be taken care of :)

**Comment by thaidn** [comment]
That's great! Just to make sure I don't step in your shoes, I'm cleaning up the code using go fmt and our internal Go style guide, so if you are working on this area, please let me know so that we can collaborate.

There are two other things that I want to tackle soon, but haven't started:

1/ Adding APIs that are present in Java/C++ but missing in Go. For example KmsClient, KeysetReader, KeysetWriter, Config, etc.

2/ One thing that I really don't like about our current code is to obtain a new cleartext keyset handle one has to do tink.CleartextKeysetHandle(). I'm not sure if this is how one does it in Go, but it looks very ugly to me. I'm thinking about moving CleartextKeysetHandle into its own package cleartext_keyset_handle or something, but then cleartext_keyset_handle won't be able to access non-public functions in the tink package, and thus won't be able to call newKeysetHandle to instantiate a new KeysetHandle. newKeysetHandle is private because we don't want users to be able to create KeysetHandle from cleartext keysets, which is a bad practice. To do that, users must use cleartext_keyset_handle which could be restricted and also stick out like a sore thumb during code review.

I'd appreciate if you folks want to help with these two projects and can share with me your thoughts on them, especially the second project.

Thanks!

**Comment by thaidn** [comment]
@gdbelvin

**Comment by gdbelvin** [comment]
Sometimes packages use the [init](https://golang.org/doc/effective_go.html#init) method to perform registration. See https://github.com/google/trillian/blob/master/crypto/keys/der/proto/register.go

**Pull request merged**
