### PR TITLE
update example instructions error

### PR DESCRIPTION
**Pull request by minnieshi**
solve #560 https://github.com/google/tink/issues/560

### CODE REVIEW

**Comment by thaidn** [comment]
Thanks. Could you please sign the CLA?

**Comment by minnieshi** [comment]
Sorry I didn't understand what you mean by sign the CLA? You mean git commit sign?

**Comment by morambro** [comment]
Hi @minnieshi could you please sign the CLA? We are otherwise unable to move on with this PR.

See https://github.com/google/tink/pull/561/checks?check_run_id=4432885603.

**Comment by chuckx** [comment]
Sorry for passing on this PR, but we can't accept contribution without a signed CLA.

This work was tackled in 7fc7fea35a864615124fd16872bc71394ad917b1. Also, as you can see in that commit, there were similar fixes to be made in neighboring files as well.

Thanks for reporting the issue.

**Pull request closed without merging**
