### PR TITLE
Google pay golang

### PR DESCRIPTION
**Pull request by Saqibm128**
Referencing #75

This is an initial implementation of the Google Pay library in Golang. Currently only decryption of the token from google pay is supported.

### CODE REVIEW

**Comment by Saqibm128** [comment]
Note: the ECIES files are from the ethereum golang implementation repository

**Comment by thaidn** [comment]
Thanks for working on this. I think this is very valuable. The PR is huge, so I wonder if you can split it up in smaller PRs, making the review easier.

For example, you can have individual PRs that implement:
* Hkdf: this should stay in subtle/kdf/hkdf.go (package is kdf)
* Common elliptic curve functions like key generation, decoding, encoding, computing shared secret, etc: this should stay in subtle/elliptic_curves.go (package is subtle)
* EciesHkdfRecipientKem and EciesHkdfSenderKem: similar to Java, should stay in subtle/hybrid/
* PaymentMethodTokenHybridEncrypt, PaymentMethodTokenHybridDecrypt, etc.: similar to Java, should stay in apps/paymentmethodtoken/go/.

What do you think?

PS: can you also revert the changes in the *.java files? Thanks!

**Comment by Saqibm128** [comment]
thank you will do

**Comment by frozenblood07** [comment]
Why is this PR closed? Is there a google pay decryption app which is in java available for golang?

**Comment by Saqibm128** [comment]
> Why is this PR closed? Is there a google pay decryption app which is in java available for golang?

There is a second version of the Google Pay API which came out after this PR and the code versioning for this never got any clear info on merging. There was also some initiative on refactoring the golang library which would have changed all the APIs and which made too many merge conflicts to make it worth retrying.

I made a separate clone here and put the PR work here: https://github.com/Saqibm128/tink
This should target v1 of the google pay api and passes one of the example unit tests from the java library, but I have no clue if it would ever work with the production api; @vladgoncharenko contacted me a while back and said he used the library, you might want to reach out to him.

**Comment by frozenblood07** [comment]
I tried using this PR but it is not working `Verify()` method is failing for all google public keys. I will checkout the second PR and see if it works.

**Pull request closed without merging**
