### PR TITLE
go: Fix AWS AEAD encryption with no additional data

### PR DESCRIPTION
**Pull request by mightyguava**
When no additional data is provided (the default across languages),
the Go library is adding a

```
"encryptionContext": {
  "additionalData": null
}
```

to the request to KMS, making it incompatible with other languages.

### CODE REVIEW

**Comment by mightyguava** [comment]
Done. `TEST_SRCDIR` and `TEST_WORKSPACE` environment variables in that test makes it really hard to run btw.

**Comment by mightyguava** [comment]
Thanks for approving! I don't seem to have permissions to merge though.

**Comment by mightyguava** [comment]
Rebased. The change is no longer needed, but I think the test is still worth merging.

**Comment by przydatek** [comment]
Thanks!

**Pull request merged**
