### PR TITLE
Hashicorp Vault Integration - Java

### PR DESCRIPTION
**Pull request by JordanStopford**
Hi all,

This is my first pull request for this project so please bear with me...

This pull requests includes Hashicorp Vault integration, similar to the implementation already available for go.

If there's any other information needed or if I've missed anything please let me know.

Regards,

Jordan

### CODE REVIEW

**Comment by juergw** [comment]
I added some comments to the Python integration pull request.

**Comment by juergw** [comment]
Sorry, but there will be some delay with this. While adding some integration tests using a real vault instance, I came across an issue that was not documented: the current implementation only works for keys that are derivable. Normal keys will simply ignore the parameter"associatedData", without an error. I have now added a warning to the code, see https://github.com/tink-crypto/tink-go-hcvault/commit/2102894269b5b0c7e952c9173143689adaed375c. The problem is that we are using the "context" parameter for associated data, and not the "associatedData" parameter that was later added, after our implementation was done. We are currently discussing how we should fix this. I think we will probably add a new API in Go that uses the "associatedData" parameter.

**Comment by juergw** [comment]
Another related issue is https://github.com/tink-crypto/tink-go/issues/7. It seems that our vault AEAD implementation in some situations may return an empty ciphertext without an error in some situations. I'd like to find the cause of that, and fix that first, too.

**Comment by JordanStopford** [comment]
Hi @juergw @morambro I think we needed to make the change to use the "associatedData" field instead of "context" here - does that still need to be done prior to the next release of tink? Thank you for accepting my changes for both Java and Python integrations of Hashicorp Vault :)

**Pull request merged**
