### PR TITLE
Allow building a KmsClient with a AWSCredentialsProvider

### PR DESCRIPTION
**Pull request by ryanhall07**
Building a KmsClient should not be restricted to a properties file or
the default env vars. e.g our org uses temporary credentials from AWS
STS.

### CODE REVIEW

**Comment by thaidn** [comment]
Thanks! This will be part of 1.3.0 release.

**Comment by ryanhall07** [comment]
@thaidn thanks! Any ETA on 1.3.0?

**Comment by thaidn** [comment]
It's coming end of February.

**Comment by wesleyk** [comment]
@thaidn just checking in again, it looks like 1.3.0 is still not released. Any updated ETA?

**Comment by chuckx** [comment]
Sorry about the delay. We're nearing release readiness. At the moment, I'm finishing up updates to our repository migration tooling. We hope to start the release process within the next 2 weeks.

**Pull request merged**
